### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Token authentication requires a token to be set

### ISSUE THREAD

**Issue by markosankovic** [synapticon/oblac-drives-config-reader#1]
![Screenshot from 2019-04-15 09-13-40](https://user-images.githubusercontent.com/102078/56113685-da90d480-5f5e-11e9-8dc3-89cf8cdbf696.png)

**Comment by romyha** [comment]
@markosankovic this is about authentication with Octokit. It needs a github token to be set in esi.service.ts

**Comment by markosankovic** [comment]
> @markosankovic this is about authentication with Octokit. It needs a github token to be set in esi.service.ts which I removed for committing.

Right, but how do you plan to have support this for all users that are going to download the app from https://oblac-drives-config-reader.synapticon.com?
